services:
  database:
    image: postgres:latest
    container_name: slimy-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - slimy_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  bot:
    build: .
    container_name: slimy-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_URL: ${POSTGRES_URL_DOCKER}
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./:/app
    command: ["sh", "-c", "chmod +x setup.sh && ./setup.sh && npm run start"]

volumes:
  slimy_data:
