services:
  database:
    image: postgres:latest
    container_name: slimy-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - slimy_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  bot:
    build: .
    container_name: slimy-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${POSTGRES_URL}
    depends_on:
      - database
    volumes:
      - ./:/app

volumes:
  slimy_data:
