services:
  database:
    image: postgres:latest
    container_name: slimy-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5433"
    volumes:
      - ./database:/var/postgresql/data

  slimy:
    build: ./slimy
    container_name: slimy-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./slimy:/app
