services:
  database:
    image: postgres:latest
    container_name: slimy-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # migrate:
  #   image: flyway/flyway:latest
  #   command: -url=jdbc:postgresql://database:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql migrate
  #   volumes:
  #     - ./database:/flyway/sql
  #   depends_on:
  #     - database

  slimy:
    build: ./bot
    container_name: slimy-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./bot:/app

volumes:
  pgdata:
