name: "📌 User Story"
description: "Template standard pour la rédaction d'une User Story"
title: "[User Story] "
labels: ["user-story"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 User Story

  - type: textarea
    id: description
    attributes:
      label: "📖 Description"
      description: "Brève explication de la fonctionnalité ou du besoin utilisateur."
      placeholder: "Ex: En tant qu’utilisateur, je veux pouvoir me connecter pour accéder à mon espace personnel."
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: "🎯 Goal"
      description: "Quel est l’impact ou la valeur ajoutée de cette User Story ?"
      placeholder: "Ex: Permettre aux utilisateurs de gérer leurs informations personnelles."
    validations:
      required: false

  - type: textarea
    id: personas
    attributes:
      label: "👥 Personas"
      description: "Quels utilisateurs sont concernés ?"
      placeholder: "Ex: Administrateurs, utilisateurs enregistrés, visiteurs, etc."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        ### ✅ Definition of Ready (DoR)

  - type: checkboxes
    id: dor
    attributes:
      label: "Definition of Ready"
      options:
        - label: "N/A"

  - type: markdown
    attributes:
      value: |
        ---

        ### ✅ Definition of Done (DoD)

  - type: checkboxes
    id: dod
    attributes:
      label: "Definition of Done"
      options:
        - label: "Required"

  - type: markdown
    attributes:
      value: |
        ---

        ### 🔗 Related Links
        - [GitHub Issue](#)
        - [Documentation](#)
