version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: dev-slimy-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-slimydb}
    volumes:
      - slimy_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  bot:
    image: node:20.10.0-bookworm
    container_name: dev-slimy-bot
    restart: unless-stopped
    working_dir: /app
    env_file:
      - ../.env
    environment:
      DATABASE_URL: ${POSTGRES_URL:-postgresql://postgres:password@database:5432/slimydb}
    depends_on:
      - database
    volumes:
      - ..:/app:cached
    command: sh -c "npm install && npm run dev"

volumes:
  slimy_data:
